name: plant_disease
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  
  sqflite: ^2.3.0
  path: ^1.8.3
  image_picker: ^1.0.7
  flutter_tts: ^4.2.5
  local_auth: ^3.0.1
  shared_preferences: ^2.2.2
  meta: ^1.17.0
  tflite_flutter: ^0.12.1
  image: ^4.0.17
  cupertino_icons: ^1.0.8
  local_auth_ios: ^1.1.7
  local_auth_android: ^2.0.5
  
  image_cropper: ^5.0.0 # Pudhu version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon leaf.jpeg" # Unga sariyaana file name
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/plant_disease_model.tflite
    - assets/labels.txt
    - "assets/icon leaf.jpeg" # Quotes-la kudutha dhaan space correct-ah work aagum